"""update team models

Revision ID: 03c2725f24c8
Revises: 9bb95c34bbfc
Create Date: 2026-01-24 12:37:21.632757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c2725f24c8'
down_revision: Union[str, Sequence[str], None] = '9bb95c34bbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'player_slots',
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('slot_no', sa.Integer(), nullable=False),
        sa.Column('slot_position', sa.String(length=2), nullable=False),
        sa.Column('slot_status', sa.String(), nullable=False),
        sa.Column('slot_role', sa.String(), nullable=False),

        sa.CheckConstraint("slot_no >= 1 AND slot_no <= 15", name="slot_range_check"),
        sa.CheckConstraint("slot_position IN ('GK','DF','MF','FW')", name="slot_position_check"),
        sa.CheckConstraint("slot_status IN ('Starting','Bench')", name="slot_status_check"),
        sa.CheckConstraint("slot_role IN ('Captain','Vice Captain','Member')", name="slot_role_check"),

        sa.ForeignKeyConstraint(['team_id'], ['Teams.owner_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('team_id', 'slot_no')
    )

    op.add_column(
        'Team_Players',
        sa.Column('slot', sa.Integer(), nullable=False)
    )

    op.create_unique_constraint(
        'unique_slot_per_team',
        'Team_Players',
        ['team_id', 'slot']
    )

    op.drop_constraint(
        'Team_Players_team_id_fkey',
        'Team_Players',
        type_='foreignkey'
    )

    op.create_foreign_key(
        'Team_Players_team_id_fkey',
        'Team_Players',
        'Teams',
        ['team_id'],
        ['owner_id'],
        ondelete='CASCADE'
    )

    op.drop_column('Team_Players', 'role')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team_Players', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Team_Players', type_='foreignkey')
    op.create_foreign_key(op.f('Team_Players_team_id_fkey'), 'Team_Players', 'Users', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_slot_per_team', 'Team_Players', type_='unique')
    op.drop_column('Team_Players', 'slot')
    op.drop_table('Player_Slots')
    # ### end Alembic commands ###
