"""update player table

Revision ID: dd821f2418b1
Revises: 9e674aad06de
Create Date: 2026-01-21 18:13:49.410001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd821f2418b1'
down_revision: Union[str, Sequence[str], None] = '9e674aad06de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Players', sa.Column('club', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Players', 'club')
    # ### end Alembic commands ###
